default:
  onlinecalculation-url: http://localhost:8100/online

communication:
  service:
    onlinecalculation: ${ONLINE_CALCULATION_SERVICE_URL:${default.onlinecalculation-url}}

auth:
  secret_private: 123

server:
  port:
    8092

spring:
  spring:
    security:
      filter:
        order: 5
  resources:
    static-locations: 'classpath:/static/,classpath:/static/vendor/,classpath:/static/custom/:'

security:
  filter-order: 5

# Security filter chain order.