management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  version: 1.0.0

server:
  servlet:
    context-path: /metrics


spring:
  http:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB