management:
  server:
    port: 8100
  endpoints:
    web:
      exposure:
        include: "*"
app:
  version: 1.0.0

server:
  port: 8090
  servlet:
    context-path: /metrics

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB